# Generated by Django 4.1 on 2022-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("C", "Completed"), ("P", "Pending"), ("I", "In-Progress")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(),
        ),
    ]
